In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float64


In [8]:
# Get Size
print(a.itemsize)
print(b.itemsize)

2
8


In [9]:
# Get Total Size
print(a.nbytes)
print(b.nbytes)

6
48


## Accessing/Changing specific elements, row, columns, etc

In [10]:
aList = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
aList

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
# Get a specific element [row, column]
aList[1,5]

13

In [12]:
# Get row
aList[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get column
aList[:, 2]

array([ 3, 10])

In [14]:
# More fancy [start_index:end_index: step_size]
aList[0, 1:-1:2]

array([2, 4, 6])

In [15]:
# change element
aList[1,5] = 20
print(aList)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
# change entire column
aList[:, 2] = [5] #change all cells to same number
print(aList)
aList[:, 2] = [2,6] #change each cell to a unique number
print(aList)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  2  4  5  6  7]
 [ 8  9  6 11 12 20 14]]


### 3 dimension array

In [17]:
bList = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
bList

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# Get specific element (work outside in)
print(bList[0,1,1])
print(bList[:,1,:])

4
[[3 4]
 [7 8]]


In [19]:
# replace 
bList[:,1,:] = [[9,9], [8,8]]
print(bList)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4,5), dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [24]:
# Any other numbers
np.full((4,4), 66, dtype='int32')

array([[66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66]], dtype=int32)

In [25]:
# full_like
np.full_like(aList, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.14137837, 0.22660759],
       [0.53233402, 0.52315169],
       [0.46868294, 0.89017596],
       [0.25082067, 0.91487688]])

In [31]:
# Random integer values
np.random.randint(4,7, size=(3,3))

array([[4, 5, 6],
       [4, 5, 5],
       [4, 6, 6]])

In [32]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
array1 = np.array([1,2,3])
array2 = array1.copy()
array2[0] = 100
print(array1)
print(array2)

[1 2 3]
[100   2   3]


## Mathematics

In [42]:
array4 = np.array([1,2,3,4])
array4

array([1, 2, 3, 4])

In [43]:
print(array4 + 2)
print(array4 -2)
print(array4 * 2)
print(array4 / 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [46]:
array5 = np.array([1,0,1,0])
print(array4 + array5)
print(array4 ** 2)

[2 2 4 4]
[ 1  4  9 16]


## Linear Algebra

In [49]:
matrixA = np.ones((2,3))
print(matrixA)

matrixB = np.full((3,2), 2)
print(matrixB)

print(np.matmul(matrixA, matrixB))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


## Statistics

In [50]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.min(stats, axis=1)

array([1, 4])

In [53]:
np.max(stats)

6

In [56]:
np.sum(stats)

21

## Reorganizing Arrays

In [57]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [59]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [62]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.vstack([v1,v2,v1,v2])
print(v3)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [63]:
v3[v3 > 2]

array([3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8])

In [70]:
np.any(v3 > 2)
print(v3)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
