In [1]:
# 1d Array
# Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
# Calculate the sum and average of the array elements.
# Multiply the array by a scalar value of 3.
# Slice the array to select elements from the 3rd to the 7th position.
# Compute the sum and average of the sliced array

# Multi-dimensional array
# Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
# Print the element in the second row, third column.
# Print the second row
# Print the second column
# Compute the transpose of the matrix

# Concatenation
# Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
# Concatenate the two arrays
# Sort the new array from lowest to highest
# Split the result from the previous step into two equal sized arrays

# Mathematical functions
# Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
# Compute an array that applies the mathematical sin function to the original array
# Do the same for the following mathematical functions: cos, log, exp
# Compute the mean, median, and standard deviation of each resultant array

# Boolean Indexing and Filtering
# Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
# Create a boolean array that identifies elements which are greater than 25
# Use that boolean array to filter out elements greater than 25 from the original array.

## 1d Array

In [2]:
import numpy as np
import math

In [3]:
# Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array1)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Calculate the sum and average of the array elements.
print(np.sum(array1))
print(np.mean(array1))

55
5.5


In [5]:
# Multiply the array by a scalar value of 3.
print(array1 * 3)

[ 3  6  9 12 15 18 21 24 27 30]


In [6]:
# Slice the array to select elements from the 3rd to the 7th position.
print(array1[2:7])

[3 4 5 6 7]


In [7]:
# Compute the sum and average of the sliced array
print(np.sum(array1[2:7]))

25


## Multi-dimensional array


In [8]:
# Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
array2 = np.array([[3,4,5], [6,7,8], [9,1,2]])
print(array2)

[[3 4 5]
 [6 7 8]
 [9 1 2]]


In [9]:
# Print the element in the second row, third column.
print(array2[1,2])

8


In [10]:
# Print the second row
print(array2[1,:])

[6 7 8]


In [11]:
# Print the second column
print(array2[:,1])

[4 7 1]


In [12]:
# Compute the transpose of the matrix
print(np.transpose(array2))

[[3 6 9]
 [4 7 1]
 [5 8 2]]


## Concatenation

In [13]:
# Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
array3 = np.array([5,1,4,2])
array4 = np.array([6,10,11,7])
print(array3)
print(array4)

[5 1 4 2]
[ 6 10 11  7]


In [14]:
# Concatenate the two arrays
joinArray = np.concatenate((array3, array4))
print(joinArray)

[ 5  1  4  2  6 10 11  7]


In [15]:
# Sort the new array from lowest to highest
print(np.sort(joinArray))

[ 1  2  4  5  6  7 10 11]


In [16]:
# Split the result from the previous step into two equal sized arrays
print(np.array_split(joinArray, 2))

[array([5, 1, 4, 2]), array([ 6, 10, 11,  7])]


## Mathematical functions


In [17]:
# Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
piArray = np.arange(0,4, (math.pi/2))
print(piArray)

[0.         1.57079633 3.14159265]


In [18]:
# Compute an array that applies the mathematical sin function to the original array
arrayA= ([1,2,3,4,5,6,7,8])
print(np.sin(arrayA))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]


In [19]:
# Do the same for the following mathematical functions: cos, log, exp
print(np.cos(arrayA))
print(np.log(arrayA))
print(np.exp(arrayA))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]


In [20]:
# Compute the mean, median, and standard deviation of each resultant array
sinArray = np.sin(arrayA)
print(sinArray)
cosArray= np.cos(arrayA)
print(cosArray)
logArray= np.log(arrayA)
print(logArray)
expArray = np.exp(arrayA)
print(expArray)
print("sin-mean:", np.mean(sinArray))
print("sin-median:", np.median(sinArray))
print("sin-std:", np.std(sinArray))

print("cos-mean:", np.mean(cosArray))
print("cos-median:", np.median(cosArray))
print("cos-std:", np.std(cosArray))

print("log-mean:", np.mean(logArray))
print("log-median:", np.median(logArray))
print("log-std:", np.std(logArray))

print("exp-mean:", np.mean(expArray))
print("exp-median:", np.median(expArray)) 
print("exp-std:", np.std(expArray))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
sin-mean: 0.19288637460820296
sin-median: 0.39905330338932815
sin-std: 0.7278383053981057
cos-mean: 0.04159425556315294
cos-median: 0.06908107582730638
cos-std: 0.6567466525151575
log-mean: 1.3255753628431561
log-median: 1.4978661367769954
log-std: 0.6579655683239042
exp-mean: 589.2780153686525
exp-median: 101.50565456786042
exp-std: 968.1783023221099


## Boolean Indexing and Filtering


In [24]:
#Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
arrayB = np.arange(15, 81, 5)
arrayC= np.sort(np.append(arrayB, 12))
print(arrayB)
print(arrayC)


[15 20 25 30 35 40 45 50 55 60 65 70 75 80]
[12 15 20 25 30 35 40 45 50 55 60 65 70 75 80]


In [42]:
# Create a boolean array that identifies elements which are greater than 25
arrayD = arrayC > 25
print(arrayD)

[False False False False  True  True  True  True  True  True  True  True
  True  True  True]


In [23]:
# Use that boolean array to filter out elements greater than 25 from the original array.

In [43]:
arrayG = np.delete(arrayC, arrayD)
print(arrayG)

[12 15 20 25]
